version: '3.7'
services:
  ready-bot:
    container_name: ready-bot-${BOT_ENV}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "BOT_TOKEN=${BOT_TOKEN}"
        - "BOT_ID=${BOT_ID}"
        - "DBL_TOKEN=${DBL_TOKEN}"